import HelpCenterAccordion from '@/components/HelpCenterAccordion';
import DocumentList from '@/components/DocumentList';
import VideoGrid from '@/components/VideoGrid';
import { manuals, datasheets, downloads } from '@/lib/resourceDocuments';

export const metadata = {
  title: 'Resources | Teracom Solutions',
  description: 'Help centre, FAQs, user manuals, datasheets and product videos for Teracom Solutions products and services.',
};

export default function Resources(){return <main><section className="hero hero-product"><div className="container hero-layout"><div className="hero-copy"><span className="eyebrow">Resources</span><h1>Documentation, manuals and support.</h1><p className="lead">We know that finding the right information can be difficult and time consuming -- this page brings it together in one place.</p></div></div></section><section className="section section-spacious"><div className="container"><div className="section-heading left"><span className="eyebrow">Help Centre &amp; FAQs</span><h2>Technical help, straight from the people who install this gear.</h2><p>We know that finding the right information can be difficult and time consuming. Below are our technical help articles, covering the camera, recorder and app technology behind our systems -- if you can&apos;t find what you&apos;re after, <a href="/#contact" style={{color:'var(--text)',textDecoration:'underline'}}>contact us</a> and we&apos;ll deal with your query promptly.</p></div><HelpCenterAccordion /></div></section><section className="section section-spacious alt"><div className="container"><div className="section-heading left"><span className="eyebrow">User Manuals</span><h2>Product manuals for the systems we supply and install.</h2></div><DocumentList documents={manuals} emptyMessage="User manuals are being added here." /></div></section><section className="section section-spacious"><div className="container"><div className="section-heading left"><span className="eyebrow">Datasheets</span><h2>Technical specification sheets.</h2></div><DocumentList documents={datasheets} emptyMessage="Datasheets are being added here." /></div></section><section className="section section-spacious alt"><div className="container"><div className="section-heading left"><span className="eyebrow">Product Videos</span><h2>Installation, configuration and product overview videos.</h2></div><VideoGrid /></div></section><section className="section section-spacious"><div className="container"><div className="section-heading left"><span className="eyebrow">Downloads</span><h2>Software, firmware and supporting documents.</h2></div><DocumentList documents={downloads} emptyMessage="Downloads are being added here." /></div></section></main>}
