import Image from 'next/image';
import { pageMetadata } from '@/lib/seo';
export const metadata = pageMetadata({
  title: 'About Teracom Solutions | Technology, Security & AI, Carrum Downs VIC',
  description: 'Teracom Solutions are leaders in technology, security and AI solutions in Australia -- Australian owned and operated, with offices in Melbourne and Sydney.',
  path: '/about',
});

export default function About(){return <main id="main-content"><section className="hero hero-product"><div className="container hero-layout"><div className="hero-copy"><span className="eyebrow">About</span><h1>Bringing tomorrow&apos;s solutions to clients, today.</h1><p className="lead">Teracom Solutions are leaders in technology, security and AI solutions in Australia.</p></div><div className="hero-image hero-blend"><Image src="/assets/teracom-storefront-van.webp" alt="Tera, the Teracom mascot, outside a Teracom Solutions building beside a Teracom service van" width={1536} height={1024} sizes="(max-width: 980px) 100vw, 55vw" priority /></div></div></section><section className="section section-spacious"><div className="container about-layout"><div className="copy-block"><p>As a proudly Australian owned and operated business, Teracom Solutions understands the requirements of the modern electrical, security and technology industries, and the issues clients can face when sourcing a complete end-to-end solution.</p><p>We are passionate about providing our customers with not only the latest and best products available at a competitive price, but also with exceptional customer service, advice and support.</p><p>Our team of engineers, electricians, technologists and business experts is carefully selected from world class organisations to bring together a multi-faceted group with decades of experience across multiple fields, dedicated to efficient sourcing and integration of multiple services and products.</p><p>With offices in Melbourne and Sydney, manufacturing partners in Australia and China, and partnerships with global brands, we are constantly finding new ways to exceed our clients&apos; expectations.</p></div><div style={{border:'1px solid var(--line)',borderRadius:'22px',padding:'36px',background:'rgba(255,255,255,.03)'}}><h3 style={{marginTop:0}}>Visit our showroom</h3><address style={{fontStyle:'normal',color:'var(--muted)',lineHeight:1.8}}>Teracom Solutions<br/>1B Yazaki Way<br/>Carrum Downs, Victoria, 3201<br/>Australia<br/><br/><a href="mailto:sales@teracomsolutions.com.au" style={{color:'var(--text)'}}>sales@teracomsolutions.com.au</a><br/><br/><strong style={{color:'var(--text)'}}>Working hours</strong><br/>Weekdays: 9am – 4:30pm<br/>Weekend: Closed</address></div></div></section></main>}
