import Link from 'next/link';
import { Download, FileText } from 'lucide-react';

import Breadcrumbs from '@/components/Breadcrumbs';
import TermsDocument from '@/components/TermsDocument';
import { pageMetadata, BUSINESS } from '@/lib/seo';
import {
  TERMS_EFFECTIVE,
  TERMS_PDF,
  TERMS_PDF_NAME,
  TERMS_VERSION,
  termsAcceptanceRecord,
  termsParts,
  termsPreamble,
  termsVersionHistory,
} from '@/lib/termsDocument';

// The PDF is regenerated by hand after each amendment to the source
// document, so it can lag the page by hours. A download that disagrees with
// the page it sits on is worse than no download, so the button only appears
// once the matching PDF has been committed to public/legal/. Flip this to
// true in the same commit that adds the file -- never before it.
const PDF_AVAILABLE = false;

export const metadata = pageMetadata({
  title: 'Terms & Conditions of Trade | Teracom Solutions',
  description: `Teracom Solutions Terms and Conditions of Trade, version ${TERMS_VERSION}, effective ${TERMS_EFFECTIVE}. General terms plus schedules for store orders, installation, monitoring and the Teracom AI platform.`,
  path: '/terms',
});

export default function TermsPage() {
  return (
    <main id="main-content" className="terms-page">
      <section className="section">
        <div className="container">
          <Breadcrumbs items={[]} current="Terms & Conditions" />
          <span className="eyebrow">Legal</span>
          <h1>Terms and Conditions of Trade</h1>
          <p className="terms-version">
            ABN {BUSINESS.abn} &nbsp;|&nbsp; Version {TERMS_VERSION} &nbsp;|&nbsp; Effective {TERMS_EFFECTIVE}
          </p>
          <div className="terms-actions">
            {PDF_AVAILABLE ? (
              <a className="btn btn-primary" href={TERMS_PDF} download={TERMS_PDF_NAME}>
                <Download size={18} strokeWidth={1.9} aria-hidden="true" focusable="false" />
                Download as PDF
              </a>
            ) : null}
            <Link className={PDF_AVAILABLE ? 'btn btn-secondary' : 'btn btn-primary'} href="/acceptable-use">
              Acceptable Use Policy
            </Link>
          </div>

          <div className="terms-layout">
            <nav className="terms-contents" aria-label="Contents">
              <h2>Contents</h2>
              <ol>
                {termsParts.map((part) => (
                  <li key={part.id}>
                    <a href={`#${part.id}`}>{part.title}</a>
                    {part.id === 'part-a' ? (
                      <ol className="terms-contents-sub">
                        {part.sections
                          .filter((section) => section.number)
                          .map((section) => (
                            <li key={section.id}>
                              <a href={`#${section.id}`}>
                                {section.number}. {section.heading}
                              </a>
                            </li>
                          ))}
                      </ol>
                    ) : null}
                  </li>
                ))}
              </ol>
            </nav>

            <article className="terms-body">
              <div className="terms-preamble">
                {termsPreamble.map((block, i) =>
                  block.type === 'heading' ? <h2 key={i}>{block.text}</h2> : <p key={i}>{block.text}</p>
                )}
              </div>

              <TermsDocument parts={termsParts} />

              {termsAcceptanceRecord.length > 0 ? (
                <table className="terms-table">
                  <caption className="visually-hidden">
                    The record Teracom keeps for each electronic acceptance of these terms
                  </caption>
                  <thead>
                    <tr>
                      <th scope="col">Field</th>
                      <th scope="col">Example</th>
                    </tr>
                  </thead>
                  <tbody>
                    {termsAcceptanceRecord.map((row) => (
                      <tr key={row.field}>
                        <th scope="row">{row.field}</th>
                        <td>{row.example}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : null}

              {termsVersionHistory ? (
                <p className="terms-history">
                  <FileText size={16} strokeWidth={1.8} aria-hidden="true" focusable="false" />
                  {termsVersionHistory}
                </p>
              ) : null}

              <p className="form-note">
                Superseded versions remain available:{' '}
                <Link href="/terms/2026-09-09">Terms and Conditions dated 9 September 2026</Link>.
              </p>
            </article>
          </div>
        </div>
      </section>
    </main>
  );
}
