// Brand/manufacturer copy for the "Brands We Work With" section.
//
// Where real narrative existed in the pre-rebuild teracomsolutions.com.au
// site (recovered via the Wayback Machine -- see
// ~/crewai/uploads/wayback-archive/ on the VM), it's been cleaned up and
// rewritten here in our own words rather than copy-pasted, but kept
// factually faithful to what the source said. Brands where the archive only
// had a product listing (or no archive source at all) get a short, honest
// paragraph based on well-known public facts instead of an invented "why we
// chose them" story -- those are flagged with needsInput: true so the page
// can point people at Robert for the fuller story.
//
// logoFile is only set for the 7 brands that already have a logo asset in
// public/assets/logos/ (matches app/page.js's partnerLogos list). Every
// other brand has no sourced logo file, so its index/detail card falls back
// to a plain heading, same as categories without artwork elsewhere on the
// site.
export const brands = [
  {
    slug: 'inner-range',
    name: 'Inner Range',
    tagline: 'Unified access control, intrusion and smart building systems, trusted across 25 countries.',
    body: `Inner Range builds access control and intruder alarm systems used across some of the world's most demanding sites, from single-door installations through to multi-site global deployments. An access control system replaces traditional keyed locks with a combination of electronic locks and identification devices -- card readers, smartphone and smartwatch credentials, fingerprint readers and facial recognition cameras -- so you can grant or restrict access to any area, at any time, and change that instantly rather than re-keying a building. Intrusion detection works alongside it: motion detectors, door reed switches and infrared beams pick up unauthorised entry, and the system can alert a monitoring centre, on-site security or a smartphone the moment it happens. Inner Range's Multipath IP monitoring adds encrypted IP and cellular communication paths to a monitoring station, so critical alarm information keeps getting through even if one path fails.

What sets Inner Range apart is how far that unification goes. Rather than running access control and intrusion as two separate systems, Inner Range combines them -- and, through its Integriti platform's integrations, extends into CCTV, lighting, intercoms, heating, cooling, visitor management and other third-party systems -- all managed from a single interface. That reduces equipment, installation and maintenance costs, and means operators only need to learn one piece of software rather than several. Cyber security is treated as an ongoing effort rather than a one-off feature, with products, systems and processes updated as threats evolve.

Inner Range systems have been installed on more than 50,000 sites across 25 countries, backed by a global network of over 5,000 certified system integrators and more than 30 years in the field. The software is intuitive enough for non-security-expert users to operate day to day, from simple apps through to smartwatches, and an Integriti licence is a one-off purchase rather than an ongoing subscription -- unlike much of the enterprise access control market, there are no lock-in annual licence fees driving up the total cost of ownership over time.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'inner-range.png',
    imageFile: 'inner-range-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Unified security that scales with you.',
    stats: [
      { value: '50,000+', label: 'Sites installed', icon: 'sites' },
      { value: '25', label: 'Countries', icon: 'countries' },
      { value: '5,000+', label: 'Certified integrators', icon: 'networking' },
      { value: '30+', label: 'Years in the field', icon: 'years' },
    ],
    highlights: [
      { title: 'Unified by Design', body: "Access control and intrusion run as one system, not two -- extending through Integriti into CCTV, lighting, intercoms, HVAC and visitor management from a single interface.", icon: 'unify' },
      { title: 'Multipath IP Monitoring', body: 'Encrypted IP and cellular paths to the monitoring centre, so critical alarm signals keep getting through even if one path fails.', icon: 'multipath' },
      { title: 'No Lock-In Licensing', body: 'An Integriti licence is a one-off purchase, not an annual subscription -- unlike much of the enterprise access control market.', icon: 'no-lockin' },
      { title: 'Built for Scale', body: 'From a single-door install to a multi-site global deployment, with software intuitive enough for non-expert operators day to day.', icon: 'scale' },
      { title: 'Flexible Credentials', body: 'Card readers, smartphone and smartwatch credentials, fingerprint readers and facial recognition -- choose how people get through the door.', icon: 'facial-recognition' },
      { title: 'Cybersecurity, Continuously', body: 'Treated as an ongoing effort rather than a one-off feature, with products, systems and processes updated as threats evolve.', icon: 'cyber-security' },
    ],
  },
  {
    slug: 'aritech',
    name: 'Aritech',
    tagline: 'Modular intrusion and access control hardware, built on the Tecom Challenger platform.',
    body: `Aritech is the brand under which Kidde Global Solutions now sells the Tecom Challenger security platform -- a modular intrusion and access control system Teracom has worked with for years under its earlier Tecom Challenger name. At the heart of a Challenger system is the Challenger panel itself: a modular, "add as you go" design that scales by adding intelligent door and lift controllers, input/output expanders, memory expanders and LAN devices as a site grows, with multiple panels able to link together under one piece of management software. That means a solution can start at a single office and expand to a multi-site environment without being re-engineered from scratch, combining intrusion detection, access control and video surveillance integration into one interface.

The current hardware range covers a few tiers. The Network Access Controller manages door and access requirements and supports intrusion applications, and can connect directly to management software or to a ChallengerPlus panel for combined access and intrusion capability. ChallengerPlus is the higher-capacity option, built for commercial and corporate environments such as banks, retail and education, with thousands of programmable options and compatibility with UltraSync and the TecomPlus mobile app. ChallengerLEPlus is the compact, cost-effective version for locations where panel space is limited, offering most of the same advanced features along with an encrypted UltraSync connection to a monitoring station and mobile app control.

On the software side, installers can program a Challenger system on site or remotely over a modem or IP connection, and end users manage doors, alarms and video surveillance through Security Commander, including an interactive map of the building for quick operator control. The TecomPlus mobile app extends day-to-day control to a phone -- arming and disarming areas, opening doors, isolating inputs and checking input/relay status -- and the wider software suite provides integrated management across multiple systems from one place.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'aritech.png',
    imageFile: 'aritech-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Modular security engineered to grow with your site.',
    stats: [
      { value: '50+', label: 'Years in the field', icon: 'years' },
      { value: '35+', label: 'Years of Challenger', icon: 'unify' },
    ],
    highlights: [
      { title: 'One Platform, Every Layer', body: 'Tecom/Forcefield unifies intrusion, access control and video into a single integrated system, so operators manage doors, alarms, cameras, recorders and intercoms from one screen instead of juggling separate consoles.', icon: 'unify' },
      { title: 'Add-As-You-Grow Design', body: "Challenger's modular architecture lets you add door or lift controllers, I/O expanders, memory expanders and LAN devices to the same panel, scaling from a single site to an enterprise footprint without ripping anything out.", icon: 'scale' },
      { title: 'Proven Since 1989', body: 'The Challenger control panel has protected Australian and New Zealand sites since 1989, and the current ChallengerPlus and Discovery ranges are built directly on that same field-tested architecture.', icon: 'years' },
      { title: "Upgrade, Don't Replace", body: 'ChallengerPlus and Discovery are designed so existing Tecom customers can move up in hardware and capability while protecting their original investment, including the ability to revert to Challenger10 firmware if needed.', icon: 'no-lockin' },
      { title: 'Designed and Made in Australia', body: 'Discovery hardware is designed, developed and manufactured in Australia, keeping engineering and production close to the market it serves.', icon: 'sites' },
    ],
  },
  {
    slug: 'honeywell',
    name: 'Honeywell',
    tagline: 'UL-listed intrusion panels, keypads and the Tuxedo Touch automation controller.',
    body: `Honeywell Security's VISTA range covers control panels, keypads and communication products for intrusion detection, built to integrate with access control, CCTV and long-range radio alongside Honeywell's own burglary components. Honeywell offers a wide variety of keypads to suit different installations, from straightforward alphanumeric keypads through to touchscreen models with graphic, menu-driven prompts that guide a user through arming, disarming and day-to-day operation, plus a broad communications range for reliably getting alarm signals off site.

The Tuxedo Touch controller extends a VISTA system into home and business automation. It's a 7-inch touchscreen that centralises control of the security system, video cameras and Z-Wave-enabled devices -- thermostats, lights, locks and shades -- from one interface, with voice commands for common actions like arming the system or adjusting the temperature when leaving or returning home. It also runs a built-in web server for local control from any Wi-Fi-enabled device, connects up to 32 IP cameras (viewing up to four at once on the display or remotely), and supports up to 30 customisable scenes that trigger based on time, day or system events.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'honeywell.svg',
    imageFile: 'honeywell.jpg',
    theme: 'access-control',
    highlightsHeading: 'Three decades of reliability, fully connected.',
    stats: [
      { value: '30+', label: 'Years of VISTA', icon: 'years' },
      { value: '150M+', label: 'Homes protected', icon: 'sites' },
      { value: '100', label: 'Countries', icon: 'countries' },
    ],
    highlights: [
      { title: 'Three Decades Proven', body: 'VISTA panels have delivered over 30 years of reliable service across millions of installations, giving the platform one of the largest installed bases in the security industry.', icon: 'years' },
      { title: 'One App, Full Control', body: 'The Total Connect 2.0 app lets customers arm and disarm the system, view live video and manage lights, locks and thermostats remotely, turning a VISTA panel into a connected security hub.', icon: 'networking' },
      { title: 'Purpose-Built Alarm Network', body: 'AlarmNet is a dedicated communications network built specifically for the security industry, handling alarm reporting, uploading/downloading and remote panel management.', icon: 'multipath' },
      { title: 'Hybrid, Not Either/Or', body: 'VISTA hybrid systems combine hardwired and wireless zones on a single panel, so installers can fit the technology to the building instead of forcing an all-wireless or all-wired retrofit.', icon: 'unify' },
      { title: 'One Panel, Many Roles', body: 'Commercial VISTA control panels integrate burglary detection, CCTV and access control functions in a single panel, cutting down the number of separate systems on a site.', icon: 'scale' },
    ],
  },
  {
    slug: 'cisco',
    name: 'Cisco',
    tagline: 'Global networking hardware for secure, reliable connectivity.',
    body: `Cisco is one of the world's largest networking equipment manufacturers, known for enterprise and small business switches, wireless access points, routers and network security products. We supply Cisco networking hardware -- including managed PoE switches and Aironet wireless access points -- as part of the network infrastructure behind the CCTV, access control and other systems we install, where reliable, secure connectivity between devices matters as much as the security equipment itself.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'cisco.svg',
    imageFile: 'cisco-showcase.svg',
    theme: 'networking',
    highlightsHeading: 'Networking infrastructure that scales from edge to cloud.',
    stats: [
      { value: '40+', label: 'Years of innovation', icon: 'years' },
      { value: '190+', label: 'Countries reached', icon: 'countries' },
      { value: '20M+', label: 'People trained', icon: 'networking' },
      { value: '$56.7B', label: 'FY25 revenue', icon: 'scale' },
    ],
    highlights: [
      { title: 'One Dashboard, Whole Network', body: 'Catalyst switches and access points connect into the Meraki cloud dashboard for single-pane-of-glass visibility, monitoring and troubleshooting across hybrid on-premises and cloud-managed networks.', icon: 'networking' },
      { title: 'Threat Intelligence Built In', body: "Cisco Talos is one of the largest commercial threat intelligence teams in the industry, feeding real-world threat research directly into Cisco's security and networking products.", icon: 'cyber-security' },
      { title: 'Four Decades of Networking', body: "Cisco has spent over 40 years building the infrastructure that runs the internet, from its earliest routers to today's Catalyst and Meraki hardware.", icon: 'years' },
      { title: 'A Global Trained Workforce', body: 'Cisco Networking Academy has trained more than 20 million people in over 190 countries since 1997, building the bench of Cisco-certified talent that keeps networks running.', icon: 'countries' },
      { title: 'Flexible Deployment, Your Way', body: "Catalyst hardware can be managed on-premises with traditional tools or fully cloud-managed through Meraki, letting customers choose or combine both approaches as their network evolves.", icon: 'scale' },
    ],
  },
  {
    slug: 'kantech',
    name: 'Kantech',
    tagline: 'Access control hardware and EntraPass management software.',
    body: `Kantech is an access control brand within the Tyco Security Products portfolio -- one of the largest security product portfolios in the world, spanning video security, access control, intrusion and location-based security. The Kantech range covers door controllers (including the KT-1 and KT-400 families), card and key fob readers, and the EntraPass management software, which handles cardholders, access levels, schedules, video and reporting from a single application, with a mobile app for installers and administrators managing systems on the go.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'kantech.jpg',
    imageFile: 'kantech-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Access control that scales from one door to thousands.',
    stats: [
      { value: '40+', label: 'Years in access control', icon: 'years' },
      { value: '400+', label: 'Doors per system', icon: 'scale' },
      { value: '20+', label: 'Tasks via mobile app', icon: 'networking' },
    ],
    highlights: [
      { title: 'One Software, Any Scale', body: 'EntraPass scales from Special Edition for a single-controller office up to Global Edition for thousands of doors across airports and government facilities, all in the same software family.', icon: 'scale' },
      { title: 'Encrypted at the Door', body: 'ioSmart readers use AES 128-bit encryption and mutual authentication between card and reader, protecting against credential cloning at the point where access control systems are most often attacked.', icon: 'cyber-security' },
      { title: 'Running in Minutes', body: 'The KT-1 controller is PoE-powered with single-button enrollment and built-in web configuration -- connect it to an IP network and it\'s ready, with no dedicated host system required in standalone mode.', icon: 'unify' },
      { title: "Upgrade Without Starting Over", body: 'Sites can move from EntraPass Special Edition to Corporate or Global Edition as they grow, protecting the original controller investment instead of ripping out hardware to scale up.', icon: 'no-lockin' },
      { title: 'Mobile-First Management', body: 'The EntraPass mobile app gives operators real-time control of more than 20 security tasks -- creating cards, locking or unlocking doors, arming partitions and viewing live video -- from a phone.', icon: 'networking' },
    ],
  },
  {
    slug: 'uniview',
    name: 'UNV / Uniview',
    tagline: 'A leading global IP video surveillance manufacturer with a full camera, NVR and software line-up.',
    body: `Uniview (UNV) is a pioneer and one of the largest manufacturers in IP video surveillance, having introduced IP video surveillance to the Chinese market before growing into a global player -- by 2018 it held the fourth-largest global market share in video surveillance, and has filed for more than 600 patents related to CCTV technology.

The UNV product line covers the full surveillance chain -- IP cameras, NVRs, encoders, decoders, storage, and client software and apps -- deployed across retail, commercial, industrial, education and city surveillance projects. We supply UNV's camera and NVR range, including PTZ, turret and dome cameras with smart IR ranges up to 250 metres and edge storage options, as a cost-effective option within our CCTV offering.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'uniview.svg',
    imageFile: 'uniview-showcase.svg',
    theme: 'cctv',
    highlightsHeading: 'AIoT security engineered for real deployments.',
    stats: [
      { value: '200+', label: 'Countries and regions', icon: 'countries' },
      { value: '5,200+', label: 'Patents applied', icon: 'cyber-security' },
      { value: '20,000+', label: 'Global partners', icon: 'networking' },
      { value: '15+', label: 'Years in business', icon: 'years' },
    ],
    highlights: [
      { title: 'ABCI Technology Core', body: 'Uniview builds its platform around four converging technologies -- Artificial Intelligence, Big Data, Cloud Computing and IoT -- giving every camera and NVR a shared AI backbone rather than bolted-on analytics.', icon: 'unify' },
      { title: 'R&D-Led Engineering', body: "More than 10% of annual revenue goes back into R&D, with over half of Uniview's global workforce sitting in R&D roles across 6 R&D centers and 2 R&D institutes.", icon: 'scale' },
      { title: 'Deep Patent Portfolio', body: 'Uniview has filed more than 5,200 patents, with over 80% classified as invention patents -- the highest-value patent category, reflecting real engineering investment rather than cosmetic design tweaks.', icon: 'cyber-security' },
      { title: 'Proven Across Verticals', body: '540+ large industrial park deployments, 300+ commercial landmark buildings, 110+ airport installations and 900+ transportation sites -- deployment depth, not just lab specs.', icon: 'sites' },
      { title: 'Global Supply Backbone', body: 'Two manufacturing bases and five warehouses spanning Europe, the Americas, the Middle East and Asia keep stock moving to over 20,000 partners across 200+ countries and regions.', icon: 'networking' },
    ],
  },
  {
    slug: 'beward',
    name: 'Beward',
    tagline: 'IP intercom systems with facial recognition, SIP compatibility and push notifications.',
    body: `Beward was established in 2004 as a developer and manufacturer of IP cameras, and has since built up a strong line of IP intercom and door station products alongside its camera range. Its IP video intercoms combine access control and two-way talk with an IP camera for motion alarm and recording, and its facial recognition models allow automatic access without any extra hardware -- the whole system can run on an existing LAN with no internet connection required, or extend to WAN use with DDNS and UPnP support.

Beward's intercom units support a 3-channel controller for connecting third-party devices such as electric locks, lights or a garage door, and are compatible with any SIP-based phone system or PBX, alongside free management software and Android/iOS apps. For sites still running analog door stations, Beward also makes converters -- including a 4-wire analog-to-SIP converter -- that turn an existing analog video door station into a SIP video intercom controllable from a PC or smartphone.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'beward.svg',
    imageFile: 'beward-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Enterprise video intercoms, built for reliability.',
    stats: [
      { value: '20+', label: 'Years in business', icon: 'years' },
      { value: 'ISO 9001', label: 'Certified quality system', icon: 'cyber-security' },
      { value: '<1%', label: 'Factory defect rate', icon: 'scale' },
    ],
    highlights: [
      { title: 'Enterprise-Only Focus', body: 'Beward explicitly excludes low-cost consumer-grade IP video gear from its lineup, engineering instead for professional and enterprise security deployments.', icon: 'scale' },
      { title: 'Standalone Face Recognition', body: 'The DS Series door stations run facial recognition locally on the device -- access decisions still work with no network or internet connection.', icon: 'facial-recognition' },
      { title: 'Efficient Video Compression', body: "Beward's B1000-series systems are built to use 20-30% less bandwidth and up to 30% less storage than standard systems, while delivering higher image quality.", icon: 'cctv' },
      { title: 'ISO 9001 Manufacturing', body: 'Production, warranty service and software development all run under ISO 9001:2015 certification, backed by a factory defect rate under 1%.', icon: 'cyber-security' },
      { title: 'Built for Local Conditions', body: 'Beward engineers its hardware for local climate, power and market conditions rather than shipping a one-size-fits-all global spec.', icon: 'countries' },
      { title: 'Multi-Actuator Access Control', body: 'DS06MP-series door stations can drive up to three actuators from one unit -- doors, gates, barriers and alarms -- cutting the extra hardware other intercoms need.', icon: 'intercoms' },
    ],
  },
  {
    slug: 'everki',
    name: 'Everki',
    tagline: 'Laptop bags and travel accessories backed by a limited lifetime warranty.',
    body: `Everki designs laptop bags, backpacks and travel accessories -- from checkpoint-friendly airport bags through to wheeled laptop trolleys -- built for people who carry a laptop for a living. The range is backed by a limited lifetime warranty against defects in materials and workmanship. We stock a selection of Everki bags and cases as an accessory line alongside our core security and networking products.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'everki.png',
    imageFile: 'everki-showcase.svg',
    theme: 'accessories',
    highlightsHeading: 'Built for travel, backed for life.',
    stats: [
      { value: '20+', label: 'Years in business', icon: 'years' },
      { value: '2M+', label: 'Bags shipped', icon: 'scale' },
      { value: 'Lifetime', label: 'Warranty coverage', icon: 'no-lockin' },
      { value: '41', label: 'Countries field-tested', icon: 'countries' },
    ],
    highlights: [
      { title: 'Limited Lifetime Warranty', body: 'Everki backs every bag with a Limited Lifetime Warranty against defects in materials and workmanship -- repaired or replaced at their discretion, for as long as the original owner has it.', icon: 'no-lockin' },
      { title: 'Checkpoint-Friendly Design', body: 'The laptop compartment opens flat 180 degrees so bags pass through airport X-ray scanners without removing the laptop -- built for frequent flyers, not just commuters.', icon: 'scale' },
      { title: 'Patented Corner-Guard Protection', body: 'A patented corner-guard system with molded-to-fit corners and extra laptop-pocket padding protects devices from the drops and knocks that travel actually causes.', icon: 'cyber-security' },
      { title: 'Designed by a Traveler', body: "Everki's founder built the brand after traveling through 41 countries as a mobile professional, designing bags around real travel friction rather than office use alone.", icon: 'countries' },
      { title: 'Two Million Bags and Counting', body: 'Since launching in 2005, Everki has shipped more than 2,000,000 bags, with a track record built on repeated long-haul travel, not showroom durability.', icon: 'sites' },
    ],
  },
  {
    slug: 'ion',
    name: 'ION',
    tagline: 'Uninterruptible power systems for industrial, retail and data centre applications.',
    body: `ION supplies uninterruptible power system (UPS) and power management products, aimed at applications where a power interruption is costly -- from industrial equipment and point-of-sale systems through to data centres and other critical IT infrastructure. We stock ION UPS units as part of our power protection range for electronic security and IT installations.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'ion.png',
    imageFile: 'ion-showcase.svg',
    theme: 'power',
    highlightsHeading: 'Power protection, engineered right here in Australia.',
    stats: [
      { value: '3-Year', label: 'Replacement warranty', icon: 'no-lockin' },
      { value: '24/7', label: 'Phone support', icon: 'networking' },
      { value: '500kVA', label: 'Largest system size', icon: 'ups' },
    ],
    highlights: [
      { title: 'Designed in Australia', body: 'ION designs its UPS systems locally in Australia, engineering for local power conditions rather than adapting an overseas catalogue.', icon: 'sites' },
      { title: 'Wi-Fi Enabled Fleet', body: "ION's UPS range ships Wi-Fi enabled as standard, for remote monitoring without extra hardware.", icon: 'networking' },
      { title: '24/7 Local Support', body: 'Phone support runs around the clock for clients and partners, backed by an advance-replacement warranty so a faulty unit is collected and replaced at no extra cost.', icon: 'multipath' },
      { title: 'Single-Phase to 3-Phase Scale', body: 'The lineup runs from 650VA line-interactive units up through 3-phase modular systems scaling to 500kVA, covering everything from a desktop to a data hall under one brand.', icon: 'scale' },
      { title: 'Lithium-ion Options', body: 'The F18L Online UPS range offers lithium-ion battery technology in the same footprint as standard online models, for longer battery life and a smaller footprint.', icon: 'ups' },
    ],
  },
  {
    slug: 'powershield',
    name: 'PowerShield',
    tagline: 'An Australian UPS manufacturer, purpose-built for the local market.',
    body: `PowerShield is an Australian power protection company that designs and manufactures uninterruptible power systems (UPS) and power filtration products specifically for the Australian market, rather than adapting an overseas range. The focus is on delivering clean, reliable power quality, and that focus -- combined with strong customer support -- has helped PowerShield grow into one of Australia's largest independent UPS manufacturers.

The range spans from smaller line-interactive units for individual equipment protection up to true online double-conversion tower and rack UPS systems with hot-swappable batteries, suiting everything from single-device backup through to larger security, IT and access control installations that need power protection they can rely on.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'powershield.png',
    imageFile: 'powershield-showcase.svg',
    theme: 'power',
    highlightsHeading: 'Clean power, engineered for Australian conditions.',
    stats: [
      { value: '2000', label: 'Founded in', icon: 'years' },
      { value: '5-Year', label: 'Warranty (LiFePO4 UPS)', icon: 'no-lockin' },
      { value: '100%', label: 'Australian owned and operated', icon: 'sites' },
    ],
    highlights: [
      { title: 'Built for Australian Conditions', body: 'PowerShield designs its UPS and power filtration range specifically for the Australian and Oceania region, rather than adapting overseas products to local conditions.', icon: 'countries' },
      { title: 'Local Engineering, Local Support', body: 'As a fully Australian owned and operated company based in Malaga, WA, PowerShield backs every install with local, professional support rather than an offshore call centre.', icon: 'sites' },
      { title: 'Trusted in Mission-Critical Sectors', body: 'PowerShield equipment protects radio stations, government, defense, security, healthcare, mining, process control and server rooms across the region.', icon: 'cyber-security' },
      { title: 'LiFePO4 Battery Technology', body: 'Lithium iron phosphate battery options extend UPS lifespan and come backed by a 5-year warranty, well beyond the 2-year standard on lead-acid models.', icon: 'ups' },
      { title: 'Warranty You Can Extend for Free', body: "Registering a Commander or Centurion single-phase unit unlocks a free warranty upgrade, PowerShield's way of standing behind its own build quality.", icon: 'no-lockin' },
    ],
  },
  {
    slug: 'reliance',
    name: 'Reliance (XR Pro)',
    tagline: 'Intrusion panels with built-in IP and 4G communication, from single-home to multi-site commercial.',
    body: `The Reliance XR Pro is an intrusion alarm panel built around built-in IP communication and encrypted connections, with two wireless receivers on board -- one for legacy 60-bit ITI wireless devices and one for the newer, fully encrypted 80Plus wireless range -- so existing Reliance equipment stays compatible as a site upgrades. It runs on the UltraSync platform for a monitored communication path with multiple levels of redundancy, and stores user codes on the panel itself as an added layer of security. An optional dual-SIM 4G/Wi-Fi module adds cellular alarm reporting and remote connection over the mobile network, and the panel is NBN-ready.

The XR Pro scales from 16 zones up to 176, with up to 256 user pin codes, suiting everything from a single residence through to multi-storey, education, retail, government, aged care and warehousing sites. Native IP camera support and Z-Wave compatibility bring camera integration and automation -- lights, door locks, heating -- into the same system, controllable either through compatible touchscreens like the XR Touch or via the UltraSync+ mobile app, which lets a user arm and disarm the system, check door and window status, and view live or recorded camera footage from anywhere.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: null,
    imageFile: 'reliance-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Engineered to protect your existing investment.',
    highlights: [
      { title: 'UltraSync Platform', body: "The XR Pro is part of the UltraSync family of intrusion panels, giving it a monitored IP communication path with encrypted connections rather than a bolt-on afterthought.", icon: 'multipath' },
      { title: 'True Hybrid Bus Design', body: 'It runs both the newer 4-wire XR bus for current expansion modules and the legacy 3-wire NX or Reliance bus, so existing wiring and peripherals keep working.', icon: 'unify' },
      { title: 'Built for Retrofit', body: "Panels are purpose-designed to drop into sites that already run older NX or Reliance panels, protecting a customer's existing hardware investment rather than forcing a full rip-and-replace.", icon: 'no-lockin' },
      { title: 'Flexible Wireless Options', body: 'An onboard 433MHz receiver supports both legacy 63-bit and newer fully-encrypted 80plus wireless accessories, with an optional 4G/WiFi module for cellular backup.', icon: 'networking' },
      { title: 'Built-In Web Management', body: 'A built-in web server handles control, user administration and panel programming directly, with firmware that is field-upgradeable as the platform evolves.', icon: 'cyber-security' },
    ],
  },
  {
    slug: 'dsc',
    name: 'DSC (PowerSeries Neo)',
    tagline: 'A comprehensive hybrid intrusion system supporting wired and PowerG wireless devices.',
    body: `DSC's PowerSeries Neo is positioned as one of the most comprehensive hybrid intrusion systems on the market, built for flexible scalability with a range of expansion modules as a site's requirements grow. It supports PowerG, DSC's encrypted two-way wireless protocol, which gives the reliability of a wired system without the cost and disruption of running cable to every sensor.

The range includes both LCD and touchscreen keypads, with interactive emulators available to help installers and end users get familiar with the interface before it's on the wall. Visual verification -- linking video to an alarm event -- is treated as a core part of a modern installation rather than an add-on, letting a monitoring operator or end user confirm what actually triggered an alert rather than reacting to a signal alone.`,
    isOwnBrand: false,
    needsInput: false,
    logoFile: 'dsc.gif',
    imageFile: 'dsc-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Intrusion security that verifies before it alarms.',
    stats: [
      { value: '2km', label: 'PowerG wireless range', icon: 'multipath' },
      { value: '128-bit', label: 'AES encryption', icon: 'cyber-security' },
      { value: '8-Year', label: 'Wireless battery life', icon: 'years' },
      { value: '128', label: 'Zones per panel', icon: 'scale' },
    ],
    highlights: [
      { title: 'PowerG Wireless Technology', body: '128-bit AES encrypted, frequency-hopping wireless with up to 2km line-of-sight range, dynamically routing around interference and jamming attempts.', icon: 'multipath' },
      { title: 'Layered Alarm Verification', body: 'PowerSeries Neo combines visual (PIR camera), audio and sequential event verification to confirm a real intrusion before dispatching a response, cutting false alarms.', icon: 'facial-recognition' },
      { title: 'Hybrid-Ready Panels', body: 'PowerSeries Neo mixes hardwired and PowerG wireless devices on the same panel, so installers can retrofit hard-to-wire sites without ripping out existing cabling.', icon: 'unify' },
      { title: 'Backed by Johnson Controls', body: "DSC's engineering is backed by the global R&D and manufacturing scale of Johnson Controls, one of the world's largest building and security technology companies.", icon: 'scale' },
      { title: 'Built for Fewer Callbacks', body: 'PowerG devices optimise their signal route to the panel automatically, extending wireless sensor battery life up to 8 years and reducing maintenance visits.', icon: 'no-lockin' },
    ],
  },
  {
    slug: 'teraudio',
    name: 'Teraudio',
    tagline: 'Our own in-house range of in-ceiling and architectural speakers.',
    body: `Teraudio is our own speaker range, engineered for home interiors -- easy to install, with paintable grilles designed to disappear into any decor rather than stand out as visible equipment. The range covers in-ceiling speakers in polypropylene and Kevlar woofer options with silk dome tweeters, digital power amplifiers (including Bluetooth-enabled models), and an 8-inch in-ceiling speaker with a built-in Wi-Fi amplifier for zones where running speaker cable isn't practical. Installation is designed to be straightforward, with cut-out templates and gold-plated spring-loaded terminals in the box, and an adjustable tweeter to focus high frequencies toward the listening area.`,
    isOwnBrand: true,
    needsInput: false,
    logoFile: 'teraudio.png',
    imageFile: 'teraudio-showcase.svg',
    theme: 'audio',
    highlightsHeading: 'Sound that disappears into the room.',
    highlights: [
      { title: 'Architecturally Invisible', body: 'Paintable grilles designed to disappear into any decor, rather than stand out as visible equipment.', icon: 'unify' },
      { title: 'Premium Drivers', body: 'Polypropylene and Kevlar woofer options with silk dome tweeters, for accurate, detailed sound.', icon: 'audio' },
      { title: 'Wi-Fi Without the Wiring', body: "An 8-inch in-ceiling speaker with a built-in Wi-Fi amplifier, for zones where running speaker cable isn't practical.", icon: 'networking' },
      { title: 'Built for Installers', body: 'Cut-out templates and gold-plated spring-loaded terminals in the box, with an adjustable tweeter to focus high frequencies toward the listening area.', icon: 'scale' },
    ],
  },
  {
    slug: 'teravision',
    name: 'TeraVision',
    tagline: 'Our own video surveillance range, built on CCTV experience dating back to 1990.',
    body: `TeraVision is our own video surveillance range, covering IP and HD-over-coax cameras, NVRs and XVRs, built for everything from small business installations through to enterprise-scale CCTV. We've been working in the electronic security, automation and CCTV industry in Australia since 1990, and that experience shapes the TeraVision range -- cameras and recorders that support AHD, CVI, TVI, IP and analog inputs on the one recorder, so a mixed-generation camera fleet doesn't need to be replaced all at once.

The range is supported by the BitVision app for remote viewing and playback from a phone, facial recognition on compatible models, and cloud backup to Dropbox or Google Drive alongside local storage. Recorders and cameras connect through iVMS320 client software on PC or Mac, with an IP search tool to find devices on a network, and every product line -- fisheye, PTZ, indoor and outdoor cameras -- comes with its own quick-start guide and user manual to make installation straightforward for installers and end users alike.`,
    isOwnBrand: true,
    needsInput: false,
    logoFile: 'teravision.png',
    imageFile: 'teravision-showcase.svg',
    theme: 'cctv',
    highlightsHeading: 'CCTV experience since 1990, built into every camera.',
    stats: [
      { value: '35+', label: 'Years CCTV experience', icon: 'years' },
      { value: '5', label: 'Formats on one recorder', icon: 'cctv' },
    ],
    highlights: [
      { title: 'Any Camera, One Recorder', body: 'Supports AHD, CVI, TVI, IP and analog inputs on the one recorder, so a mixed-generation camera fleet doesn\'t need replacing all at once.', icon: 'cctv' },
      { title: 'Remote by Default', body: 'The BitVision app gives remote viewing and playback from a phone, with facial recognition on compatible models.', icon: 'facial-recognition' },
      { title: 'Cloud or Local, Your Choice', body: "Cloud backup to Dropbox or Google Drive alongside local storage, so footage isn't reliant on one single point of failure.", icon: 'no-lockin' },
      { title: 'Installer-Friendly', body: 'Every product line ships with its own quick-start guide and user manual, plus an IP search tool in iVMS320 to find devices on a network fast.', icon: 'scale' },
    ],
  },
  {
    slug: 'ubiquiti',
    name: 'Ubiquiti',
    tagline: 'Wireless networking and the UniFi ecosystem for wired and wireless connectivity at scale.',
    body: `Ubiquiti Networks makes wireless networking, switching and routing hardware, best known for its UniFi ecosystem of access points, switches, gateways and cloud key controllers that manage a whole network from one interface, plus its airMAX and airFiber range for long-range point-to-point and point-to-multipoint wireless links. We stock a wide range of Ubiquiti access points, switches and antennas as part of the networking infrastructure behind our security and connectivity installations.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'ubiquiti.svg',
    imageFile: 'ubiquiti-showcase.svg',
    theme: 'networking',
    highlightsHeading: 'One ecosystem. Zero subscriptions. Total control.',
    stats: [
      { value: '2003', label: 'Founded', icon: 'years' },
      { value: '200+', label: 'Countries and territories', icon: 'countries' },
      { value: '6', label: 'Native UniFi apps', icon: 'networking' },
      { value: '$0', label: 'Monthly cloud fees', icon: 'no-lockin' },
    ],
    highlights: [
      { title: 'One Console, Every Site', body: 'UniFi Network unifies gateways, switches, access points and cameras in a single interface with real-time topology, managing unlimited sites from anywhere.', icon: 'networking' },
      { title: 'Zero Recurring Fees', body: "No per-device licenses and no monthly cloud subscriptions -- just ownership, with software updates included for free.", icon: 'no-lockin' },
      { title: 'Security Beyond Networking', body: 'UniFi Protect (AI-driven camera platform) and UniFi Access (touchscreen door readers and mobile credentials) extend the same login and console into physical security.', icon: 'cyber-security' },
      { title: 'Enterprise-of-Things Reach', body: 'UniFi Connect extends the ecosystem into digital signage, lighting and EV charging stations, turning the network into shared infrastructure for the whole site.', icon: 'scale' },
      { title: 'Built to Scale Without Breaking', body: 'A redundant architecture designed to grow effortlessly from starter setups to massive global deployments, with no single point of failure.', icon: 'unify' },
    ],
  },
  {
    slug: 'genetec',
    name: 'Genetec',
    tagline: 'Unified security software combining video management, access control and analytics.',
    body: `Genetec is a Canadian technology company best known for Security Center, a unified security platform that brings video management, access control, automatic license plate recognition and other security applications together in one system rather than running them as separate products. Genetec's software is widely used across large, multi-site enterprise, government, transportation and retail security deployments.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'genetec.svg',
    imageFile: 'genetec-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Unified security, built on an open platform.',
    stats: [
      { value: '1997', label: 'Founded', icon: 'years' },
      { value: '159+', label: 'Countries served', icon: 'countries' },
      { value: '42,500+', label: 'Customers worldwide', icon: 'scale' },
      { value: '2,100+', label: 'Employees', icon: 'networking' },
    ],
    highlights: [
      { title: 'One Truly Unified Platform', body: 'Security Center natively combines video (Omnicast), access control (Synergis) and license plate recognition (AutoVu) in one operator interface, not separate systems bolted together.', icon: 'unify' },
      { title: 'Open Architecture', body: 'Built to integrate with over 10,000 third-party devices and systems, so customers choose the best camera or hardware for the job instead of being locked to one vendor.', icon: 'no-lockin' },
      { title: 'Privacy Protection Built In', body: 'The KiwiVision Privacy Protector module anonymises people in live and recorded video by default, among the first video products to carry a GDPR-ready privacy seal.', icon: 'cyber-security' },
      { title: 'Mission Control PSIM', body: 'Genetec Mission Control turns Security Center into a decision-support system that automates incident workflows across video, access and intrusion events without custom scripting.', icon: 'multipath' },
      { title: 'Hybrid-Cloud, Your Pace', body: 'Cloudlink appliances and Security Center SaaS bring existing camera and access control hardware to the cloud, letting customers migrate on their own timeline instead of a forced rip-and-replace.', icon: 'scale' },
    ],
  },
  {
    slug: 'gallagher',
    name: 'Gallagher',
    tagline: 'Gallagher Security -- access control and perimeter security for high-security sites.',
    body: `Gallagher Security (a division of Gallagher Group, distinct from the company's agricultural fencing business) makes access control, perimeter security and intrusion detection systems, with a strong presence in government, defence, airport and other high-security environments. Its Command Centre software platform integrates access control, monitoring and perimeter detection into a single management interface.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'gallagher.png',
    imageFile: 'gallagher-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'Security built for high-stakes sites, at any scale.',
    stats: [
      { value: '35+', label: 'Years designing security', icon: 'years' },
      { value: '140+', label: 'Countries trusted in', icon: 'countries' },
      { value: '20,000+', label: 'Security customers worldwide', icon: 'scale' },
      { value: '15%', label: 'Of revenue invested in R&D', icon: 'cyber-security' },
    ],
    highlights: [
      { title: 'Command Centre, One Platform', body: 'Command Centre unifies access control, intruder alarms and perimeter security in a single system that scales from one door to thousands.', icon: 'unify' },
      { title: 'Designed and Built In-House', body: "Gallagher designs and manufactures its own hardware and software at its global headquarters, giving Teracom clients a vertically integrated stack instead of stitched-together third-party parts.", icon: 'sites' },
      { title: 'Cyber-Hardened by Default', body: 'The C7000 controller is built for modern cyber defense, backed by ISO 27001:2022 and SOC 2 Type II accreditation across Gallagher\'s security practices.', icon: 'cyber-security' },
      { title: 'Trusted for High-Security Sites', body: 'Gallagher is an approved supplier to Five Eyes governments and is deployed across defense, critical infrastructure, mining and healthcare sites where failure is not an option.', icon: 'countries' },
      { title: 'Continuous R&D Investment', body: 'Gallagher reinvests 15% of annual revenue into R&D, keeping the platform ahead of emerging threats rather than relying on legacy hardware.', icon: 'scale' },
    ],
  },
  {
    slug: 'hid',
    name: 'HID',
    tagline: 'HID Global -- access control credentials, readers and identity management.',
    body: `HID Global is one of the largest suppliers of access control credentials, readers and identity management technology worldwide, spanning physical access cards and fobs, mobile and biometric credentials, and identity verification systems. HID's card and reader technology underpins a large share of the access control systems installed globally, often working behind the scenes as a component within a wider access control platform.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'hid.svg',
    imageFile: 'hid-showcase.svg',
    theme: 'access-control',
    highlightsHeading: 'The credential technology behind global identity.',
    stats: [
      { value: '35+', label: 'Years in identity security', icon: 'years' },
      { value: '100+', label: 'Countries served', icon: 'countries' },
      { value: '4,500+', label: 'Employees worldwide', icon: 'networking' },
    ],
    highlights: [
      { title: 'Seos Credential Technology', body: "HID's Seos technology decouples security from the physical card, using strong cryptography so the same trusted credential works across cards, mobile devices and wearables.", icon: 'cyber-security' },
      { title: 'HID Signo Readers', body: 'Signo is the current-generation reader line, built to support nearly every credential technology in one device -- Seos, iCLASS SE, iCLASS, MIFARE DESFire, 125kHz Prox and Bluetooth/NFC mobile credentials.', icon: 'unify' },
      { title: 'True Mobile Access', body: 'HID Mobile Access turns a smartphone or smartwatch into a credential, with native support for both iOS and Android rather than a single-platform workaround.', icon: 'networking' },
      { title: 'Backed by ASSA ABLOY', body: "As part of the ASSA ABLOY group since 2000, HID combines a focused identity R&D team with the scale and longevity of the world's largest access solutions group.", icon: 'scale' },
    ],
  },
  {
    slug: 'axis',
    name: 'Axis',
    tagline: 'Axis Communications -- the company that invented the network camera.',
    body: `Axis Communications is a Swedish manufacturer credited with releasing the world's first network camera, and remains one of the leading names in IP video surveillance, along with network audio, access control and analytics products. Axis cameras are widely specified in enterprise and government surveillance projects, and the company places a strong emphasis on open standards and cybersecurity in its product design.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'axis.svg',
    imageFile: 'axis-showcase.svg',
    theme: 'cctv',
    highlightsHeading: 'The company that invented the network camera.',
    stats: [
      { value: '1996', label: 'Invented the network camera', icon: 'years' },
      { value: '50+', label: 'Countries operated in', icon: 'countries' },
      { value: '5,000+', label: 'Employees worldwide', icon: 'networking' },
      { value: '40+', label: 'Years in operation', icon: 'scale' },
    ],
    highlights: [
      { title: 'Invented the Category', body: "Axis launched the AXIS Neteye 200 in 1996, the world's first network camera -- the product that created the IP video surveillance industry.", icon: 'cctv' },
      { title: 'Open Standards From Day One', body: 'Axis avoided proprietary protocols from inception, building on open standards so its cameras integrate freely with third-party VMS platforms instead of locking customers in.', icon: 'no-lockin' },
      { title: 'Custom Silicon: ARTPEC', body: 'Axis designs its own ARTPEC image-processing chipset in-house, purpose-built for video security rather than repurposed consumer camera hardware.', icon: 'cyber-security' },
      { title: 'Edge Vault Cybersecurity', body: 'Edge Vault is a hardware-based cybersecurity toolkit embedded in the camera itself, protecting device identity and firmware integrity at the edge, not just in the network.', icon: 'cyber-security' },
      { title: 'Lightfinder and Forensic WDR', body: 'Axis-developed imaging technologies like Lightfinder (colour in near-darkness) and Forensic WDR (detail in high-contrast scenes) are built for evidence quality, not just picture quality.', icon: 'cctv' },
    ],
  },
  {
    slug: 'milestone',
    name: 'Milestone',
    tagline: 'Milestone Systems -- open-platform video management software.',
    body: `Milestone Systems, a Denmark-based company owned by Canon, makes XProtect, one of the most widely deployed open-platform video management software (VMS) systems in the industry. Being open-platform means XProtect is designed to work with cameras and hardware from many different manufacturers rather than locking a customer into one vendor's camera range, which is a big part of why it's used across such a broad range of surveillance deployments.`,
    isOwnBrand: false,
    needsInput: true,
    logoFile: 'milestone.svg',
    imageFile: 'milestone-showcase.svg',
    theme: 'cctv',
    highlightsHeading: 'Open by design, since the first SDK shipped.',
    stats: [
      { value: '25+', label: 'Years in open-platform VMS', icon: 'years' },
      { value: '150+', label: 'Countries represented in', icon: 'countries' },
      { value: '8,000+', label: 'Partners worldwide', icon: 'networking' },
      { value: '1,000+', label: 'Technology integrations', icon: 'unify' },
    ],
    highlights: [
      { title: 'The Open Platform Philosophy', body: 'Milestone built its business model around openness, releasing the industry\'s first VMS software development kit in 2005 to enable third-party innovation on top of XProtect.', icon: 'unify' },
      { title: 'No Camera Lock-In', body: "XProtect integrates with thousands of camera and device models from well over a hundred manufacturers, so Teracom clients aren't forced onto a single hardware vendor.", icon: 'no-lockin' },
      { title: 'Backed by Canon, Run Independently', body: 'Milestone has operated as a standalone company within the Canon Group since 2014, pairing long-term financial backing with continued independence on its open-platform roadmap.', icon: 'scale' },
      { title: 'Milestone Kite Cloud VMS', body: "Milestone Kite extends the same open-platform thinking to the cloud, offering a simple, secure, scalable cloud VMS for sites that don't want to manage on-prem servers.", icon: 'multipath' },
      { title: 'A Genuine Partner Ecosystem', body: 'Over 8,000 technology partners, developers and resellers build on XProtect, giving customers a far deeper integration library than a closed, single-vendor system could offer.', icon: 'networking' },
    ],
  },
];

export function findBrand(slug) {
  return brands.find((b) => b.slug === slug);
}
