export const heroSlides = [
  {
    id: 'industry-ai',
    eyebrow: 'AI.Technology',
    headline: 'Industry expertise and AI innovation, built for the real world.',
    body: 'Teracom combines deep industry knowledge across electronic security, audio visual, electrical, automation and systems integration with modern consulting, software and AI-powered solutions to help organisations design, deliver and support smarter systems.',
    image: '/assets/hero-technology.svg',
    imageAlt: 'Abstract technology dashboard for security and AI',
    ctaHref: '/securityos-ai',
    ctaLabel: 'Explore Teracom AI',
    secondaryHref: '#what-we-do',
    secondaryLabel: 'View What We Do',
  },
  {
    id: 'store-account',
    eyebrow: 'Teracom Store',
    headline: 'Create a free account to view pricing and shop the store.',
    body: 'Sign up in a couple of minutes to see real pricing on every product and start building your order.',
    image: '/assets/store-preview.svg',
    imageAlt: 'Teracom Store product preview',
    ctaHref: '/account/signup',
    ctaLabel: 'Create your account',
    secondaryHref: '/store',
    secondaryLabel: 'Browse the Store',
  },
  {
    id: 'brands',
    eyebrow: 'Our Partners',
    headline: 'Backed by the security industry\'s leading manufacturers.',
    body: 'Teracom works with Gallagher, Inner Range, Genetec, HID, Axis and more -- see the full list of brands we support.',
    image: '/assets/hero-technology.svg',
    imageAlt: 'Teracom brand partners',
    ctaHref: '/brands',
    ctaLabel: 'View All Brands',
    secondaryHref: null,
    secondaryLabel: null,
  }
];