// Homepage hero banner slides. `isPlaceholder: true` marks a slide whose
// copy/image is a stand-in written by Claude (2026-09-13), not real
// marketing content -- these 4 exist to fill out the carousel to Robert's
// requested 7 slides ahead of the Global Platform's marketing-managed CMS
// (see HERO_BANNER_FEATURE_BRIEF.md) being built. Whoever builds that CMS
// migration, or edits this file directly in the meantime, should replace
// every `isPlaceholder: true` entry's content with real specials/manufacturer
// updates/Teracom AI news -- the 3 non-placeholder slides are real and
// should NOT be treated as needing replacement.
export const heroSlides = [
  {
    id: 'industry-ai',
    isPlaceholder: false,
    eyebrow: 'AI.Technology',
    headline: 'Industry expertise and AI innovation, built for the real world.',
    body: 'Teracom combines deep industry knowledge across electronic security, audio visual, electrical, automation and systems integration with modern consulting, software and AI-powered solutions to help organisations design, deliver and support smarter systems.',
    image: '/assets/hero-tera-intelligence.webp',
    imageAlt: 'Tera, the Teracom mascot -- real intelligence builds a safer tomorrow',
    ctaHref: '/securityos-ai',
    ctaLabel: 'Explore Teracom AI',
    secondaryHref: '#what-we-do',
    secondaryLabel: 'View What We Do',
  },
  {
    id: 'store-account',
    isPlaceholder: false,
    eyebrow: 'Teracom Store',
    headline: 'Create a free account for member pricing.',
    body: 'Prices are shown to everyone -- sign up in a couple of minutes to unlock additional member discounts across the store.',
    image: '/assets/store-preview.svg',
    imageAlt: 'Teracom Store product preview',
    ctaHref: '/account/signup',
    ctaLabel: 'Create your account',
    secondaryHref: '/store',
    secondaryLabel: 'Browse the Store',
  },
  {
    id: 'brands',
    isPlaceholder: false,
    eyebrow: 'Our Partners',
    headline: 'Backed by the security industry\'s leading manufacturers.',
    body: 'Teracom works with Gallagher, Inner Range, Genetec, HID, Axis and more -- see the full list of brands we support.',
    image: '/assets/hero-bigger-together.webp',
    imageAlt: 'Tera looking out over a city at sunset -- bigger together',
    ctaHref: '/brands',
    ctaLabel: 'View All Brands',
    secondaryHref: null,
    secondaryLabel: null,
  },
  // --- Placeholder slides below: marketing/dev to replace, see file header ---
  {
    id: 'placeholder-special-offer',
    isPlaceholder: true,
    eyebrow: 'Special Offer',
    headline: 'Seasonal savings across selected security hardware.',
    body: 'Ask our team about current promotions on access control, video and intrusion products from our partner brands.',
    image: '/assets/hero-technology.svg',
    imageAlt: 'Teracom special offer',
    ctaHref: '/store',
    ctaLabel: 'Shop the Store',
    secondaryHref: null,
    secondaryLabel: null,
  },
  {
    id: 'placeholder-teracom-ai-update',
    isPlaceholder: true,
    eyebrow: 'Teracom AI News',
    headline: 'The latest from the Teracom AI platform.',
    body: 'New capabilities and updates are rolling out regularly -- see what\'s new for Teracom AI customers.',
    image: '/assets/hero-security-command-centre.webp',
    imageAlt: 'Tera at a security command centre -- real intelligence for a safer world',
    ctaHref: '/securityos-ai',
    ctaLabel: 'See What\'s New',
    secondaryHref: null,
    secondaryLabel: null,
  },
  {
    id: 'placeholder-manufacturer-spotlight',
    isPlaceholder: true,
    eyebrow: 'Manufacturer Spotlight',
    headline: 'This month, we\'re spotlighting one of our key partners.',
    body: 'Discover the latest products and technology from the manufacturers Teracom works with every day.',
    image: '/assets/hero-stronger-together.webp',
    imageAlt: 'Tera training -- stronger, smarter, safer together',
    ctaHref: '/brands',
    ctaLabel: 'View Brands',
    secondaryHref: null,
    secondaryLabel: null,
  },
  {
    id: 'placeholder-new-arrivals',
    isPlaceholder: true,
    eyebrow: 'New Arrivals',
    headline: 'Fresh stock, newly listed in the Teracom Store.',
    body: 'Browse newly added products across our full range of security and technology categories.',
    image: '/assets/store-preview.svg',
    imageAlt: 'New arrivals in the Teracom Store',
    ctaHref: '/store/new-arrivals',
    ctaLabel: 'Browse New Arrivals',
    secondaryHref: null,
    secondaryLabel: null,
  },
];
