// Free installer calculators shown on /tools. `config: true` tools are driven by
// lib/toolConfigs.js; the rest have their own component in components/tools
// (see CUSTOM_CALCULATORS in app/tools/[slug]/page.js). `group` sets the section
// on /tools and the icon pattern behind each calculator.
export const toolGroups = [
  { id: 'cctv', eyebrow: 'CCTV & video', title: 'Plan cameras, storage and recording.' },
  { id: 'power', eyebrow: 'Power', title: 'Size supplies, batteries, solar and UPS.' },
  { id: 'cabling', eyebrow: 'Cabling', title: 'Plan copper and fibre runs.' },
  { id: 'network', eyebrow: 'Networks', title: 'Subnets, wireless links and transfers.' },
  { id: 'av', eyebrow: 'Audio & display', title: 'Speaker lines, screens and projectors.' },
];
export const tools = [
  {
    slug: 'cctv-storage-calculator',
    group: 'cctv',
    title: 'CCTV Storage Calculator',
    description: 'Estimate how much recording storage a CCTV system needs from camera count, bitrate, recording hours and retention.',
    howItWorks: 'Storage per camera per day is the bitrate x the recording time (hours x the share of time actually recording). Multiply by the number of cameras and the retention period in days to get the total capacity the recorder needs.',
  },
  {
    slug: 'cctv-lens-calculator',
    group: 'cctv',
    config: true,
    title: 'CCTV Lens & Pixel Density Calculator',
    description: 'Check the scene width and pixels per metre a camera gives at a distance, and whether it can detect, recognise or identify a person.',
    howItWorks: "Scene width is 2 x distance x tan(half the horizontal field of view). Pixel density is the camera's horizontal resolution divided by that width. Detail levels use the IEC 62676-4 (DORI) thresholds: 25 px/m to detect, 62.5 to observe, 125 to recognise and 250 to identify; the furthest distance for each level is where the density falls to that threshold.",
  },
  {
    slug: 'cctv-bandwidth-calculator',
    group: 'cctv',
    config: true,
    title: 'CCTV Network Bandwidth Calculator',
    description: 'Work out the network bandwidth your cameras need to the recorder and for remote viewing.',
    howItWorks: "Recording bandwidth is the number of cameras x bitrate, plus an allowance for network overhead. Remote viewing adds the number of streams watched at once x their (usually lower) sub-stream bitrate -- that part has to fit within the site's internet upload speed.",
  },
  {
    slug: 'nvr-raid-planner',
    group: 'cctv',
    config: true,
    title: 'NVR Hard Drive & RAID Planner',
    description: 'Find how many drives, and what size, you need to reach a storage target at RAID 1, 5, 6 or 10.',
    howItWorks: "RAID 5 gives up one drive's capacity to parity and RAID 6 gives up two; RAID 1 and RAID 10 mirror the data, so half the raw capacity is usable. The planner adds drives until the usable capacity covers your target (respecting each level's minimum drive count), then adds any hot spares.",
  },
  {
    slug: 'cctv-bitrate-calculator',
    group: 'cctv',
    config: true,
    title: 'CCTV Bitrate Estimator',
    description: 'Estimate the bitrate a camera will stream from its resolution, frame rate, compression and how busy the scene is.',
    howItWorks: 'This uses the Kush gauge, a widely used rule of thumb: width x height x frame rate x a motion factor (1 for a quiet scene, 2 for a moderate one, 4 for a busy one) x 0.07 bits per pixel gives the H.264 bitrate. H.265 usually needs 25-50% less for the same picture, so we take 40% off. A day of continuous recording is the bitrate x 86,400 seconds.',
  },
  {
    slug: 'cctv-mounting-height-calculator',
    group: 'cctv',
    config: true,
    title: 'CCTV Mounting Height & Blind Spot Calculator',
    description: "See where a camera's view starts and ends on the ground, and the blind spot under it, from its height, tilt and lens.",
    howItWorks: 'The vertical field of view comes from the horizontal one and the image shape. The bottom edge of the image looks down at the tilt plus half the vertical view, so it meets the ground at the height divided by the tangent of that angle: that distance is the blind spot. The top edge looks down at the tilt minus half the vertical view; if that angle is zero or less, the image reaches the horizon. The same sums at head height show where people come into view.',
  },
  {
    slug: '4g-cctv-data-calculator',
    group: 'cctv',
    config: true,
    title: '4G CCTV Data Usage Calculator',
    description: 'Work out how much mobile data a 4G camera uses in a month from live viewing, event clips and cloud uploads.',
    howItWorks: 'Data is bitrate x time: megabits per second x seconds, divided by 8, gives megabytes. Live viewing, event clips and any continuous upload are added up for a day, an overhead allowance goes on top, and the day is multiplied by the days in the month.',
  },
  {
    slug: 'poe-power-budget-calculator',
    group: 'power',
    title: 'PoE Power Budget Calculator',
    description: 'Add up the PoE power your cameras, access points and devices draw, and check it against your switch budget.',
    howItWorks: "Each device's power (the maximum for its PoE class, or its actual draw if you know it) is multiplied by the quantity and added up, then compared with the switch's total PoE budget and port count.",
  },
  {
    slug: 'access-control-psu-calculator',
    group: 'power',
    config: true,
    title: 'Access Control Power Supply Calculator',
    description: 'Add up the current your readers, locks and controllers draw and size the power supply with headroom.',
    howItWorks: "Total load is each device's current x quantity. The required rating adds your headroom, and the suggestion is the next common power supply size up. Use the total load in the Battery Standby Calculator to size the backup battery.",
  },
  {
    slug: 'battery-standby-calculator',
    group: 'power',
    title: 'Battery Standby Calculator',
    description: 'Work out the battery capacity an alarm or access control panel needs to cover its standby and alarm load.',
    howItWorks: 'Required capacity is (standby current x standby hours + alarm current x alarm hours) x a derating factor that allows for battery ageing and temperature. The suggestion is the next common sealed lead-acid size up.',
  },
  {
    slug: 'ups-runtime-calculator',
    group: 'power',
    config: true,
    title: 'UPS Runtime & Sizing Calculator',
    description: 'Estimate how long a UPS will run your equipment, and the UPS rating you need.',
    howItWorks: 'Battery energy is volts x amp-hours x number of batteries. Runtime is that energy x inverter efficiency divided by the load. The UPS rating is the load divided by its power factor, plus headroom, rounded up to a common UPS size.',
  },
  {
    slug: 'solar-battery-calculator',
    group: 'power',
    config: true,
    title: 'Off-Grid Solar & Battery Calculator',
    description: 'Size the solar panel, battery and charge controller for a camera or 4G router that runs off-grid.',
    howItWorks: "Daily energy is the load in watts x the hours it runs. The battery must cover that for the days with no sun, divided by the share of its capacity you can use (80% for lithium, 50% for AGM), and amp-hours are watt-hours divided by the system voltage. The panel must replace a day's energy in the worst month's peak sun hours after losses. The charge controller is the panel's current at the system voltage plus 25%.",
  },
  {
    slug: 'running-cost-calculator',
    group: 'power',
    config: true,
    title: 'Equipment Running Cost Calculator',
    description: 'Work out the yearly electricity use and cost of cameras, recorders, switches and other equipment that runs around the clock.',
    howItWorks: 'Each line is watts x quantity x hours per day, divided by 1,000 for kilowatt-hours a day. A year is 365 days, and the cost is the kilowatt-hours x your rate in cents, divided by 100.',
  },
  {
    slug: 'voltage-drop-calculator',
    group: 'cabling',
    title: 'Cable Voltage Drop Calculator',
    description: 'Check the voltage drop on a 12 V or 24 V DC cable run and find the minimum conductor size for your device.',
    howItWorks: "Current flows out to the device and back, so the calculator uses twice the one-way length. Loop resistance is that length x the resistivity of copper (0.0172 Ω·mm²/m at 20°C) divided by the conductor's cross-section; the voltage drop is the load current x that resistance. The minimum conductor size is the cross-section that keeps the drop inside your chosen limit.",
  },
  {
    slug: 'fibre-loss-budget-calculator',
    group: 'cabling',
    config: true,
    title: 'Fibre Optic Loss Budget Calculator',
    description: "Add up fibre, connection and splice losses and check the link against your optics' power budget.",
    howItWorks: "Link loss is the length in km x the fibre's attenuation in dB/km, plus the loss of each mated connection and each splice. The margin is the optics' power budget (transmit power minus receiver sensitivity) less the link loss and a safety allowance, and it should stay above zero. The default losses are the TIA-568 maximums.",
  },
  {
    slug: 'cable-quantity-calculator',
    group: 'cabling',
    config: true,
    title: 'Cable Quantity & Box Calculator',
    description: 'Work out how many metres and 305 m boxes of network cable a job needs, and check the longest run.',
    howItWorks: 'Each run is its length plus slack. The runs are added up and a waste allowance goes on top, and the boxes are that total divided by the box length, rounded up. The longest run with slack is checked against the 90 m permanent link that TIA-568 allows (100 m including patch leads).',
  },
  {
    slug: 'ip-subnet-calculator',
    group: 'network',
    config: true,
    title: 'IP Subnet Calculator',
    description: 'Work out the network, broadcast and usable address range for a camera or access control subnet.',
    howItWorks: 'The prefix length sets the subnet mask. The network address is the IP address with the host bits cleared, the broadcast address has them all set, and the usable host addresses sit between the two.',
  },
  {
    slug: 'wireless-link-calculator',
    group: 'network',
    config: true,
    title: 'Wireless Link Clearance Calculator',
    description: 'Check the clearance a point-to-point wireless link needs over trees and roofs, and its path loss.',
    howItWorks: 'The first Fresnel zone radius at the middle of the link is 17.32 x the square root of the distance in km divided by 4 x the frequency in GHz, in metres, and at least 60% of it should be clear. The earth bulges by the distance squared divided by 8 x 4/3 x 6,371 km at the midpoint. Free-space path loss is 20 log(distance in km) + 20 log(frequency in GHz) + 92.45 dB.',
  },
  {
    slug: 'data-transfer-time-calculator',
    group: 'network',
    config: true,
    title: 'Data Transfer Time Calculator',
    description: 'Work out how long a backup, footage export or file copy takes over a network link.',
    howItWorks: 'Time is the data in bytes x 8, divided by the link speed in bits per second x the efficiency you expect. The daily figure is the effective speed x 86,400 seconds, divided by 8.',
  },
  {
    slug: 'speaker-load-calculator',
    group: 'av',
    config: true,
    title: '100 V Line Speaker Load Calculator',
    description: 'Add up speaker tap wattages on a 100 V or 70 V line and check the amplifier has enough headroom.',
    howItWorks: "Total load is each speaker's tap setting x quantity. The amplifier should be rated at least that plus your headroom. The impedance the line presents to the amplifier is the line voltage squared divided by the total tap load.",
  },
  {
    slug: 'projector-throw-calculator',
    group: 'av',
    config: true,
    title: 'Projector Throw & Screen Size Calculator',
    description: 'Work out the image size a projector gives at a distance from its throw ratio, or the distance for a screen width.',
    howItWorks: 'Image width is the throw distance divided by the throw ratio; the height follows from the aspect ratio and the diagonal from both. The distance for a given screen width is that width x the throw ratio.',
  },
  {
    slug: 'screen-size-calculator',
    group: 'av',
    config: true,
    title: 'Screen Size & Viewing Distance Calculator',
    description: 'Find the right TV or display size for a viewing distance, or the best seats for a screen you have.',
    howItWorks: "A screen fills a view angle when its width is 2 x the distance x tan(half the angle), and the diagonal follows from the width and the shape. We show the widely quoted 30° (SMPTE) for general viewing and THX's 40° for an immersive seat, and for a given screen the distances where it fills 30°, and 40° down to 28°.",
  },
  {
    slug: 'projector-brightness-calculator',
    group: 'av',
    config: true,
    title: 'Projector Brightness Calculator',
    description: 'Work out the lumens a projector needs for the screen size, the room light and what the audience is watching.',
    howItWorks: 'System contrast is the light from a white image plus the room light, divided by the room light alone. To reach a target ratio the projector must add (ratio - 1) x the room light, in lux, on the screen, and lumens are that lux x the screen area in square metres. The targets are the ANSI/INFOCOMM 3M-2011 categories: 7:1, 15:1, 50:1 and 80:1.',
  },
];

export function findTool(slug) {
  return tools.find((t) => t.slug === slug);
}